### ISSUE TITLE
Python keystore over Java

### ISSUE THREAD

**Issue by nerdalertdk** [brian7704/OpenTAKServer#11]
Hi,

Would be nice if we could drop the javascript dependency for keytool :)
I'm no python programmer but found this :)

Pure-Python Java Keystore (JKS) library
https://pypi.org/project/pyjks/
https://pyjks.readthedocs.io/en/latest/

Manly asking so I don't need to include Java in the docker image I'm building for OTS.

There is a big difference in docker image size

```
ots based on python:3.12-slim = 413MB (Just have python)
ots based on python:3.12 = 1.96GB (need for build tools and JRE)
```

**Comment by brian7704** [comment]
Thanks for the suggestion, I've never seen pyjks before. I agree, dropping the dependency on keytool is a good idea. I'll try to get this into the next major release.

**Comment by brian7704** [comment]
I ended up removing JKS creation all together in version 1.1.5 so now there's no need for any java stuff in the docker image.
