### ISSUE TITLE
No path for truststore-root.jks

### ISSUE THREAD

**Issue by nerdalertdk** [brian7704/OpenTAKServer#12]
While reading the code around the use of keytool
I found that `truststore-root.jks` is placed in its "default" location

https://github.com/brian7704/OpenTAKServer/blob/4ff11d8ea8a4f23c77ef4faf72f2883e679290f1/opentakserver/certificate_authority.py#L86

Also dude please "cd ~" not a fix, its a hack 🥲 please use absolute paths <3 
you kinda doing it here https://github.com/brian7704/OpenTAKServer/blob/e94be229edf1f6c2b0f474e18c1a4d0d14b7dcfc/opentakserver/certificate_authority.py#L103

but still "cd" should not be needed.

Issue #5 could be related to `truststore-root.jks` is not in the `OTS_CA_FOLDER` folder, but looks to default to `~`

**Comment by brian7704** [comment]
I removed JKS creation in 1.1.5 so now there is no need to use PyJKS
