### ISSUE TITLE
Add OTS_LISTENER_IP option

### ISSUE THREAD

**Issue by nerdalertdk** [brian7704/OpenTAKServer#23]
Hi

For some of us that's trying to do more complex setups, it would be helpful
if we could bind flask app to `0.0.0.0` or an ip instead of `127.0.0.1 `

`OTS_LISTENER_IP=x.x.x.x`

https://github.com/brian7704/OpenTAKServer/blob/9250cea242f97b76e2c8b9833623512e9195cb9d/opentakserver/app.py#L291C62-L291C79

**Comment by nerdalertdk** [comment]
If you are gonna anything big with the config system, please consider support for ENV 
it even support a default value 👍 

https://www.geeksforgeeks.org/python-os-getenv-method/

**Comment by brian7704** [comment]
I'll add the OTS_LISTENER_IP setting to the config. I checked the Flask documentation and loading the config from environment variables seems doable. Can you please open a separate issue for that?

**Comment by brian7704** [comment]
OTS_LISTENER_IP has been added and will be included in the next release. You can install it now using `pip install git+https://github.com/brian7704/OpenTAKServer.git@f01413d`
