### ISSUE TITLE
Login doesnt work with Usernames < 4 Chars

### ISSUE THREAD

**Issue by fti7** [brian7704/OpenTAKServer#40]
Login doesnt work with Usernames < 4 Chars

xxxx = working
xxx = not working

User is anyway created in the DB.

**Comment by nerdalertdk** [comment]
https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_USERNAME_MIN_LENGTH

**Comment by brian7704** [comment]
This can be fixed by adding `SECURITY_USERNAME_MIN_LENGTH: 1` to your config.yml. I'll also add that option to defaultconfig.py.
