### ISSUE TITLE
Possible bug in data package generation may lead to connection failures to OpenTAKServer

### ISSUE THREAD

**Issue by ki6uve** [brian7704/OpenTAKServer#41]
Data package generation may be inserting the wrong path to certificate locations.  This could lead to a failure to correctly import the certificates when installing the data package on an ATAK EUD.

**Comment by brian7704** [comment]
Fixed by [5ebdbdd](https://github.com/brian7704/OpenTAKServer/commit/5ebdbdd4f5fa1ca7cdc1e49f5c23cd9a5de14736)
