### ISSUE TITLE
It is not possible to connect a WinTAK client

### ISSUE THREAD

**Issue by ferenc92** [brian7704/OpenTAKServer#46]
When trying to connect a WinTAK client (WinTAK v5.1.0.147 (CIV)), the error message ‘Failed to load client certificate for OpenTAKServer_test’ appears.
(OpenTAKServer_testis the name of the server connection)

The connection of an Abdroid client works perfectly. 
The installation of the Certificate Authority also works.

<img width="275" alt="config" src="https://github.com/user-attachments/assets/2ae4175e-d567-49be-8b54-1d39b0c383e9">
<img width="318" alt="message" src="https://github.com/user-attachments/assets/88b94503-4fa5-41bb-a113-18ad906643e5">

**Comment by brian7704** [comment]
Did you load your server's certificate where it says Install Certificate Authority?

**Comment by ferenc92** [comment]
Hello @brian7704 

Yes, I have downloaded the certificate via API:https://your_server_address/api/truststore

I have now found the solution. I had to update to WinTAK v5.2.0.153 (CIV).

**Comment by abdull6771** [comment]
i have this issue do you solve it

**Comment by ghost** [comment]
Unfortunately, I couldn't get it to work and eventually gave up. I'm now using the official TAKserver, since it just works right out of the box.
It's a shame, OpenTAKServer would actually be a great project. Especially with the integration with Meshtastic.

**Comment by abdull6771** [comment]
can you help me guide me on how you use the tak server

**Comment by abdull6771** [comment]
Hi,

I'm running into a persistent issue connecting WinTAK to my OpenTAKServer instance and could use your input.

**My setup:**
- OpenTAKServer (OTS) v1.7.11 deployed on Fly.io at a public IP (137.)
- Self-signed CA generated by OTS (named test)
- Server fully operational — Web UI accessible at https://137., all services (nginx, OTS, PostgreSQL, RabbitMQ) running
- Users created: EAGLE_1, EAGLE_2, EAGLE_3 with correct group assignments (IN+OUT direction)

**The issue:**
WinTAK on Windows fails to enroll a client certificate from the cloud server. The error rotates between:
- "The TAK server's identity could not be verified"
- "Failed to load client certificate for NAF-TAK-Cloud (C:\Users\abdul\AppData\Roaming\WinTAK\SslCerts\ClientCerts.p12)"
- "Registration failed"

The server logs show no record of WinTAK actually reaching the server, which suggests WinTAK is failing client-side on SSL validation before sending any enrollment request. I'm running WinTAK-CIV, which seems to enforce strict SSL by default with no visible toggle to disable it.

**What I've tried:**
- Cleared all WinTAK cert directories and re-added the server fresh
- Enabled "Use Authentication" with correct EAGLE_1 credentials
- Confirmed server reachable (Test-NetConnection to port 8446 succeeds)
- Confirmed user exists in OTS Admin → Users
- Looked everywhere in WinTAK Settings for "Strict SSL CA" / "Strict SSL Hostname" toggles — can't find them in CIV version

**My questions:**
1. Are there strict SSL toggles in WinTAK-CIV that I'm missing? Where?
2. What alternative TAK clients have you used successfully against self-signed OTS deployments?
3. Is the Let's Encrypt + domain name path the only real long-term fix here?

I know I can solve this with a real domain + Let's Encrypt cert (and I plan to), but I'm hoping there's a faster path to validating the deployment end-to-end first.

Any pointers appreciated.
